apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-master-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-master-app
  template:
    metadata:
      labels:
        app: session-master-app
    spec:
      containers:
      - name: session-master-app
        image: evsikovandrey/session-master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
