apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boilerplate-app
  template:
    metadata:
      labels:
        app: boilerplate-app
    spec:
      containers:
      - name: boilerplate-app
        image: evsikovandrey/boilerplate
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      - name: session-slave-app
        image: evsikovandrey/boilerplate
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
